import type { Metadata } from 'next';
import { contentContainer } from './styles/global.css';
import ClientProvider from './clientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ClientProvider>
          <div className={contentContainer}>{children}</div>
        </ClientProvider>
      </body>
    </html>
  );
}
